"""
latent_distribution_gap.py  —  Option D Diagnostic
====================================================
Compares the statistical distribution of real DINOv2 latents (from
data/processed/) against latents generated by the World Model rollout.

Measures:
  - Mean vector distance  (||μ_real - μ_wm||₂)
  - Per-dimension variance ratio  (σ²_wm / σ²_real), mean and max
  - Per-dimension mean shift      (|μ_wm - μ_real|), mean and max

Verdict:
  - Gap SMALL  → transfer failure is structural, not a stats mismatch
  - Gap LARGE  → add latent normalisation alignment in Phase 3 (step 3a)

Usage:
    python -m src.scripts.latent_distribution_gap \
        --checkpoint checkpoints/world_model_best.pt \
        --data_dir   data/processed \
        --n_episodes 50 \
        --rollout_steps 16
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import torch

from src.models.transformer import DinoWorldModel
from src.models.transformer_configuration import TransformerWMConfiguration as Config
from src.data.buffer import LatentReplayBuffer


# ── Helpers ───────────────────────────────────────────────────────────────────

def load_model(checkpoint_path: Path, device: torch.device) -> DinoWorldModel:
    config = Config()
    model  = DinoWorldModel(config).to(device)
    ckpt   = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(ckpt["model_state"])
    model.eval()
    print(f"[INFO] Loaded WM checkpoint — epoch {ckpt.get('epoch', '?')}  "
          f"loss={ckpt.get('metrics', {}).get('avg_loss', float('nan')):.6f}")
    return model


def load_buffer(data_dir: Path) -> LatentReplayBuffer:
    buf   = LatentReplayBuffer(capacity_steps=200_000)
    files = sorted(data_dir.glob("*.npz"))
    if not files:
        raise FileNotFoundError(f"No .npz files found in {data_dir}")
    for f in files:
        d = np.load(f)
        missing = [k for k in ("latents", "actions", "rewards", "dones") if k not in d]
        if missing:
            continue
        buf.add_episode(
            latents=d["latents"],
            actions=d["actions"],
            rewards=d["rewards"],
            dones=d["dones"],
        )
        d.close()
    print(f"[INFO] Buffer loaded — {len(buf.episodes)} episodes, "
          f"{buf.total_steps} steps")
    return buf


# ── Core diagnostic ───────────────────────────────────────────────────────────

def collect_real_latents(buffer: LatentReplayBuffer,
                         n_episodes: int) -> np.ndarray:
    """Return (N, 384) array of real latents sampled from the buffer."""
    episodes = buffer.episodes[:n_episodes]
    return np.concatenate([ep.latents for ep in episodes], axis=0)


@torch.no_grad()
def collect_wm_latents(model: DinoWorldModel,
                       buffer: LatentReplayBuffer,
                       n_episodes: int,
                       rollout_steps: int,
                       device: torch.device) -> np.ndarray:
    """
    For each of n_episodes, take a real z0 from the buffer and roll out
    the world model for rollout_steps steps using random actions.
    Returns (N, 384) array of WM-generated latents.
    """
    collected = []
    episodes  = buffer.episodes[:n_episodes]

    for ep in episodes:
        z0 = torch.tensor(ep.latents[0], dtype=torch.float32, device=device)
        z0 = z0.unsqueeze(0).unsqueeze(0)  # (1, 1, 384)

        actions = torch.randint(0, 4, (1, rollout_steps), device=device)
        pred_latents, _, _ = model.rollout(z0, actions)
        # pred_latents: (1, rollout_steps, 384)
        collected.append(pred_latents.squeeze(0).cpu().numpy())

    return np.concatenate(collected, axis=0)  # (N*rollout_steps, 384)


def compute_gap(real: np.ndarray, wm: np.ndarray) -> dict:
    mu_real  = real.mean(axis=0)   # (384,)
    mu_wm    = wm.mean(axis=0)
    var_real = real.var(axis=0)    # (384,)
    var_wm   = wm.var(axis=0)

    mean_dist      = float(np.linalg.norm(mu_real - mu_wm))
    mean_shift     = float(np.abs(mu_real - mu_wm).mean())
    max_shift      = float(np.abs(mu_real - mu_wm).max())

    # Avoid divide-by-zero on near-zero variance dims
    safe_var_real  = np.where(var_real < 1e-8, 1e-8, var_real)
    var_ratio      = var_wm / safe_var_real
    mean_var_ratio = float(var_ratio.mean())
    max_var_ratio  = float(var_ratio.max())

    return dict(
        mean_dist      = mean_dist,
        mean_shift     = mean_shift,
        max_shift      = max_shift,
        mean_var_ratio = mean_var_ratio,
        max_var_ratio  = max_var_ratio,
        mu_real        = mu_real,
        mu_wm          = mu_wm,
        var_real       = var_real,
        var_wm         = var_wm,
    )


def verdict(gap: dict) -> str:
    """Simple threshold-based verdict to guide Phase 3 decisions."""
    if gap["mean_dist"] > 5.0 or gap["mean_var_ratio"] > 3.0:
        return "LARGE — add latent normalisation alignment in Phase 3 (step 3a)"
    elif gap["mean_dist"] > 1.0 or gap["mean_var_ratio"] > 1.5:
        return "MODERATE — normalisation alignment recommended but may not be critical"
    else:
        return "SMALL — transfer failure is structural, not a stats mismatch"


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint",    type=str, default="checkpoints/world_model_best.pt")
    parser.add_argument("--data_dir",      type=str, default="data/processed")
    parser.add_argument("--n_episodes",    type=int, default=50)
    parser.add_argument("--rollout_steps", type=int, default=16)
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Device: {device}")

    model  = load_model(Path(args.checkpoint), device)
    buffer = load_buffer(Path(args.data_dir))

    if len(buffer.episodes) < args.n_episodes:
        print(f"[WARN] Only {len(buffer.episodes)} episodes available, "
              f"requested {args.n_episodes} — using all.")
        args.n_episodes = len(buffer.episodes)

    print(f"\n[INFO] Collecting {args.n_episodes} real episodes...")
    real_latents = collect_real_latents(buffer, args.n_episodes)

    print(f"[INFO] Rolling out WM for {args.n_episodes} episodes "
          f"× {args.rollout_steps} steps...")
    wm_latents = collect_wm_latents(model, buffer, args.n_episodes,
                                    args.rollout_steps, device)

    print(f"[INFO] Real latents shape : {real_latents.shape}")
    print(f"[INFO] WM latents shape   : {wm_latents.shape}")

    gap = compute_gap(real_latents, wm_latents)

    print(f"\n{'='*58}")
    print(f"  LATENT DISTRIBUTION GAP REPORT")
    print(f"{'='*58}")
    print(f"  Mean vector distance  (||μ_real - μ_wm||₂) : {gap['mean_dist']:.4f}")
    print(f"  Mean per-dim shift    (|μ_wm - μ_real| avg): {gap['mean_shift']:.4f}")
    print(f"  Max per-dim shift                          : {gap['max_shift']:.4f}")
    print(f"  Mean variance ratio   (σ²_wm / σ²_real)   : {gap['mean_var_ratio']:.4f}")
    print(f"  Max variance ratio                         : {gap['max_var_ratio']:.4f}")
    print(f"\n  Real latent global var : {gap['var_real'].mean():.6f}")
    print(f"  WM latent global var   : {gap['var_wm'].mean():.6f}")
    print(f"\n  VERDICT: {verdict(gap)}")
    print(f"{'='*58}\n")

    # Save affine correction parameters for Phase 3 step 3a
    out_path = Path("evaluation/latent_gap_stats.npz")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez(
        out_path,
        mu_real  = gap["mu_real"],
        mu_wm    = gap["mu_wm"],
        var_real = gap["var_real"],
        var_wm   = gap["var_wm"],
    )
    print(f"[INFO] Affine correction stats saved to {out_path}")
    print(f"       (Used in Phase 3 step 3a if gap is LARGE)")


if __name__ == "__main__":
    main()